export const GalleryActionTypes = {
  GET_GALLERY: 'GET_GALLERY',
  UPLOAD_IMAGE: 'UPLOAD_IMAGE',
  SET_GALLERY_ERROR: 'SET_GALLERY_ERROR',
  UPDATE_MAIN_IMAGE: 'UPDATE_MAIN_IMAGE',
  REMOVE_IMAGE: 'REMOVE_IMAGE'
};
