export const PostActionTypes = {
  GET_USERS_POSTS: 'GET_USERS_POSTS',
  GET_CURRENT_POST: 'SET_POST',
  REMOVE_POST: 'REMOVE_POST',
  GET_POSTS_FROM_FRIENDS: 'GET_POSTS_FROM_FRIENDS',
  POSTS_ERROR: 'POSTS_ERROR',
  LIKE_POST: 'LIKE_POST',
  DISLIKE_POST: 'DISLIKE_POST'
};
