export const UserActionTypes = {
  GET_ALL_USERS: 'GET_ALL_USERS',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  REMOVE_CURRENT_USER: 'REMOVE_CURRENT_USER',
  SET_USER_ERROR: 'SET_USER_ERROR',
  GET_SINGLE_USER: 'GET_SINGLE_USER',
  ADD_EDUCATION: 'ADD_EDUCATION',
  REMOVE_EDUCATION: 'REMOVE_EDUCATION',
  ADD_EXPERIENCE: 'ADD_EXPERIENCE',
  REMOVE_EXPERIENCE: 'REMOVE_EXPERIENCE',
  ADD_FRIEND: 'ADD_FRIEND',
  REMOVE_FRIEND: 'REMOVE_FRIEND',
  SEND_FRIEND_REQUEST: 'SEND_FRIEND_REQUEST',
  DECLINE_FRIEND_REQUEST: 'DECLINE_FRIEND_REQUEST'
};
