export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  REMOVE_CURRENT_USER: 'REMOVE_CURRENT_USER',
  SET_USER_ERROR: 'SET_USER_ERROR',
  GET_SINGLE_USER: 'GET_SINGLE_USER',
  ADD_EDUCATION: 'ADD_EDUCATION',
  REMOVE_EDUCATION: 'REMOVE_EDUCATION',
  ADD_EXPERIENCE: 'ADD_EXPERIENCE',
  REMOVE_EXPERIENCE: 'REMOVE_EXPERIENCE'
};
